### ISSUE TITLE
grab caddy from getcaddy website, not a static executable

### ISSUE THREAD

**Issue by japharl** [dbohdan/caddy-cgi#1]
Download from https://getcaddy.com/ instead of including a static copy in github.

**Comment by dbohdan** [comment]
In the latest commits (e75b061ccdde67aed0babcda01e4aa924bff318c, 289ab20ce00aae741fd9b901101a43efee58da9b ) I removed the Caddy binary and updated the instructions to include downloading the latest one from the website.

**Comment by japharl** [comment]
Awesome, thanks.  Been using your code reliably for a while now.

**Comment by dbohdan** [comment]
You're welcome! The credit should first and foremost go to Denis S. Filimonov, who originally wrote `fastcgi-wrapper`, and Lewin Bormann who patched it.
